meta_product_name: "Famtravel"
meta_title: "Famtravel - Best tips from one parent to another"
meta_description: "Famtravel helps parents travelling in new cities to find the best child friendly places."
meta_image: "Family-travel.jpg" # should exist in `app/assets/images/`
